### ISSUE TITLE
Media Page Bug

### ISSUE THREAD

**Issue by KeksKartoffe** [rtmediawp/rtMedia#731]
Watch this and you know what i mean ^^

https://capacity-gaming.de/mitglieder/kekskartoffel/media/

**Comment by manishsongirkar** [comment]
Hello @KeksKartoffe 

It seems your theme is not supporting rtMedia plugin, Please follow the steps to fix the rtMedia template styles:

1) Add below style in `Custom CSS Settings` (https://rtmedia.io/docs/settings/custom-css/)
```css
body.media article {
    margin: 0 0 2em 0;
    padding: 1.5em;
    background: #fff;
    border-top: 3px solid #dd5533;
    box-shadow: 0 2px 2px #aaa;
    max-width: 100%;
}
```
2) Setup thumbnail sizes (https://rtmedia.io/docs/settings/image-sizes/)

Let me know if this could help you.

You can also follow the troubleshooting [document](https://rtmedia.io/docs/troubleshooting/conflict-diagnosis-guide-wordpress-plugins/).
